import { SceneMeta, CameraTransform, SceneId } from '@/types/presentation';

export const SCENES: SceneMeta[] = [
  {
    id: 'intro',
    index: 0,
    title: 'SENTINEL',
    subtitle: 'AI-Powered Anti-Money Laundering Intelligence System',
    question: 'What is Sentinel?',
    category: 'Overview',
  },
  {
    id: 'problem',
    index: 1,
    title: 'The $2.4 Trillion Challenge',
    subtitle: 'Why Legacy Rules-Based AML Systems Fail modern finance',
    question: 'Why do traditional AML systems fail?',
    category: 'Problem',
  },
  {
    id: 'journey',
    index: 2,
    title: 'Transaction Journey',
    subtitle: 'Tracking anomalous payload Tx-8809 across cross-border rails',
    question: 'How does an anomaly enter the system?',
    category: 'Pipeline',
  },
  {
    id: 'architecture',
    index: 3,
    title: 'Neural Pipeline Architecture',
    subtitle: 'Four sequential stages of real-time machine intelligence',
    question: 'How is Sentinel structured?',
    category: 'Pipeline',
  },
  {
    id: 'stage1',
    index: 4,
    title: 'Stage 1: Stream Ingestion',
    subtitle: 'Sub-millisecond ISO 20022 parsing & schema sanitization',
    question: 'How are high-volume streams processed?',
    category: 'Pipeline',
  },
  {
    id: 'stage2',
    index: 5,
    title: 'Stage 2: Feature Engineering',
    subtitle: 'Real-time extraction of 450+ dynamic temporal & velocity vectors',
    question: 'What behavioral signals are extracted?',
    category: 'Pipeline',
  },
  {
    id: 'stage3',
    index: 6,
    title: 'Stage 3: Ensemble Risk Scoring',
    subtitle: 'Unified GNN + XGBoost inference yielding real-time risk scores',
    question: 'How is risk quantified?',
    category: 'Intelligence',
  },
  {
    id: 'stage4',
    index: 7,
    title: 'Stage 4: Graph Intelligence',
    subtitle: 'Sub-network ring detection exposing multi-entity laundering hubs',
    question: 'How are hidden networks uncovered?',
    category: 'Intelligence',
  },
  {
    id: 'shap',
    index: 8,
    title: 'Explainable AI (SHAP)',
    subtitle: 'Mathematical proof & decision driver attribution for audit defense',
    question: 'Why was this flagged by AI?',
    category: 'Intelligence',
  },
  {
    id: 'fatf',
    index: 9,
    title: 'Regulatory Policy Engine',
    subtitle: 'Automated verification against FATF 40 & Travel Rule matrix',
    question: 'Is this compliant with international law?',
    category: 'Compliance',
  },
  {
    id: 'sar',
    index: 10,
    title: 'Automated SAR Generation',
    subtitle: 'Instant synthesis of FinCEN Suspicious Activity Report drafts',
    question: 'How fast can compliance teams respond?',
    category: 'Compliance',
  },
  {
    id: 'override',
    index: 11,
    title: 'Human-In-The-Loop Safety',
    subtitle: 'Cryptographic analyst signature & dual-control override panel',
    question: 'Who retains final authority?',
    category: 'Action',
  },
  {
    id: 'finale',
    index: 12,
    title: 'The Sentinel Ecosystem',
    subtitle: 'Autonomous, scalable, and continuous financial protection',
    question: 'What is the global impact?',
    category: 'Ecosystem',
  },
];

export const CAMERA_KEYFRAMES: Record<SceneId, CameraTransform> = {
  intro: {
    position: [0, 0, 18],
    target: [0, 0, 0],
    fov: 45,
    duration: 2.0,
    ease: 'power3.inOut',
  },
  problem: {
    position: [0, 0, 14],
    target: [0, 0, 0],
    fov: 50,
    duration: 1.8,
    ease: 'power2.inOut',
  },
  journey: {
    position: [-4, 1, 10],
    target: [-4, 0, 0],
    fov: 40,
    duration: 2.2,
    ease: 'expo.out',
  },
  architecture: {
    position: [0, 2, 22],
    target: [0, 0, 0],
    fov: 52,
    duration: 2.5,
    ease: 'power4.inOut',
  },
  stage1: {
    position: [-7.5, 0.5, 8.5],
    target: [-7.5, 0, 0],
    fov: 38,
    duration: 1.6,
    ease: 'power3.out',
  },
  stage2: {
    position: [-2.5, 0.5, 8.5],
    target: [-2.5, 0, 0],
    fov: 38,
    duration: 1.6,
    ease: 'power3.out',
  },
  stage3: {
    position: [2.5, 0.5, 8.5],
    target: [2.5, 0, 0],
    fov: 38,
    duration: 1.6,
    ease: 'power3.out',
  },
  stage4: {
    position: [7.5, 1.2, 10],
    target: [7.5, 0, 0],
    fov: 42,
    duration: 2.0,
    ease: 'back.out(1.1)',
  },
  shap: {
    position: [0, 0, 12],
    target: [0, 0, 0],
    fov: 45,
    duration: 1.5,
    ease: 'power2.inOut',
  },
  fatf: {
    position: [0, -0.5, 11],
    target: [0, 0, 0],
    fov: 45,
    duration: 1.5,
    ease: 'power2.inOut',
  },
  sar: {
    position: [1, 0, 9],
    target: [1, 0, 0],
    fov: 38,
    duration: 1.8,
    ease: 'power3.inOut',
  },
  override: {
    position: [0, 0, 8.5],
    target: [0, 0, 0],
    fov: 36,
    duration: 1.5,
    ease: 'power2.out',
  },
  finale: {
    position: [0, 0, 26],
    target: [0, 0, 0],
    fov: 60,
    duration: 3.0,
    ease: 'power4.inOut',
  },
};
