'use client';

import { motion } from 'framer-motion';
import { FileText, Download, Sparkles, CheckCircle2 } from 'lucide-react';
import { audio } from '@/lib/audio';

export function Scene10_SARGeneration() {
  const downloadReport = () => {
    audio.playSuccess();
    const element = document.createElement('a');
    const file = new Blob([
      `FINCEN SUSPICIOUS ACTIVITY REPORT (SAR) DRAFT
Generated by Sentinel AML AI Engine v4.2
Timestamp: ${new Date().toISOString()}

TARGET TRANSACTION: Tx-8809-994X
AMOUNT: $1,200,000.00 USD
RISK SCORE: 0.94 / 1.00 (CRITICAL)
NARRATIVE SUMMARY:
High-velocity structuring anomaly originating from Shell Corp Alpha (Cayman Islands) routed to OFAC sanctioned hub via 1-hop relay node. SHAP proof attached.
      `,
    ], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = 'FinCEN_SAR_Draft_Tx8809.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen px-6 pointer-events-auto">
      <div className="max-w-4xl w-full space-y-8">
        <div className="text-center space-y-3">
          <div className="inline-flex items-center space-x-2 px-4 py-1.5 rounded-full bg-[#C5A880]/5 border border-[#C5A880]/15 text-[#C5A880] text-xs font-mono uppercase tracking-widest">
            <Sparkles className="w-4 h-4 text-[#C5A880]" />
            <span>Automated Document Synthesis</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-medium font-serif text-white tracking-tight">
            Instant FinCEN SAR Filing Draft
          </h2>
          <p className="text-gray-400 max-w-xl mx-auto font-light leading-relaxed">
            What used to require 4.2 hours of manual analyst narrative writing is synthesized by Sentinel in 1.2 seconds, complete with attached graph evidence diagrams.
          </p>
        </div>

        {/* Live SAR Document Synthesis Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-8 rounded-3xl bg-[#141414] border border-[#222222] shadow-2xl space-y-6 text-left"
        >
          <div className="flex items-center justify-between border-b border-[#222222] pb-4">
            <div className="flex items-center space-x-3">
              <div className="p-2.5 rounded-2xl bg-[#C5A880]/10 text-[#C5A880]">
                <FileText className="w-6 h-6 text-[#C5A880]" />
              </div>
              <div>
                <h3 className="font-mono font-bold text-white text-base">FinCEN_SAR_Form_111_Draft.pdf</h3>
                <p className="text-xs text-gray-400">Auto-Generated via Sentinel LLM Compliance Model</p>
              </div>
            </div>

            <button
              onClick={downloadReport}
              className="px-4 py-2 rounded-xl bg-[#C5A880] hover:bg-[#b89b73] text-black text-xs font-semibold flex items-center space-x-2 shadow-lg shadow-black/10 transition-all"
            >
              <Download className="w-4 h-4 text-black" />
              <span>Export SAR Draft</span>
            </button>
          </div>

          {/* Document Preview Box */}
          <div className="p-5 rounded-2xl bg-black/40 border border-white/5 font-mono text-xs text-gray-300 space-y-3 leading-relaxed">
            <div className="text-[#C5A880] font-bold">SUSPICIOUS ACTIVITY REPORT NARRATIVE:</div>
            <p>
              "On August 05, 2026, Sentinel AI flagged transaction Tx-8809 ($1,200,000.00 USD) originating from Shell Corp Alpha (Cayman Islands). The transaction exhibited an extreme velocity anomaly (+840% baseline deviation) and was linked via 1-hop graph centrality to OFAC Sanctioned Entity Node #99481."
            </p>
            <div className="flex items-center space-x-2 text-[#7A9282] text-[11px]">
              <CheckCircle2 className="w-4 h-4 text-[#7A9282]" />
              <span>Attached: 3D Graph Topology Diagram & SHAP Attribution Matrix</span>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
